### ISSUE TITLE
Errors when running the tests from inside the simphony-framework

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-openfoam#27]
Running the tests from inside the simphony-framework (https://github.com/simphony/simphony-framework/pull/27) fails with the following traceback.

```python
[Mon Jun  8 16:55:32 2015] (40/40) test_run_time (foam_controlwrapper.tests.test_controlwrapper.FoamControlWrapperTestCase)
Test that field variable value is changed after ... ERROR
======================================================================
ERROR: test_run_time (foam_controlwrapper.tests.test_controlwrapper.FoamControlWrapperTestCase)
Test that field variable value is changed after
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/simphony/simphony-framework/src/simphony-openfoam/foam_controlwrapper/tests/test_controlwrapper.py", line 251, in test_run_time
    'simplemesh.cuds'))
  File "/home/travis/simphony/local/lib/python2.7/site-packages/simphony/io/h5_cuds.py", line 57, in open
    handle = tables.open_file(filename, mode, title=title)
  File "/home/travis/simphony/local/lib/python2.7/site-packages/tables/file.py", line 296, in open_file
    _FILE_OPEN_POLICY))
ValueError: The file 'foam_controlwrapper/tests/simplemesh.cuds' is already opened.  Please close it before reopening.  HDF5 v.1.8.4-patch1, FILE_OPEN_POLICY = 'strict'
======================================================================
FAIL: test_parallel_run (foam_controlwrapper.tests.test_controlwrapper.FoamControlWrapperTestCase)
Test parallel running of OpenFoam
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/simphony/simphony-framework/src/simphony-openfoam/foam_controlwrapper/tests/test_controlwrapper.py", line 313, in test_parallel_run
    if re.match(r'processor*', d)]))
AssertionError: 2 != 0
----------------------------------------------------------------------
Ran 40 tests in 1.813s
```

**Note**: using simphony-common 0.1.3

**Comment by nathanfranklin** [comment]
@khiltunen , i can pick this up if that is okay with you.

**Comment by khiltunen** [comment]
It's okay. Thank's

**Comment by nathanfranklin** [comment]
@khiltunen , I am stuck on #31 and waiting for your input.
