### ISSUE TITLE
Running wrapper with CUDS input file dependent on corresponding pimary data files

### ISSUE THREAD

**Issue by TobiasRasp** [simphony/simphony-openfoam#43]
Even after a CUDS input file was generated with foam_mesh_to_h5cuds.py from the data stored in case/constant/polyMesh/ (i.e. boundary, faces, neighbour, owner, points), it is required for a successful run to have this primary set of data files available in this folder. 
Wouldn't it be better if the CUDS file provides all the mesh information required as a stand alone file that is accordingly portable also to other cases?

**Comment by TobiasRasp** [comment]
For example if the boundary file is missing in case/constant/polyMesh/, the following error message is given:

Traceback (most recent call last):
  File "poiseuille.py", line 46, in <module>
    lastTime = wrapper.run()
  File "/W5/ras/SimPhoNy/Kopplung_CFD-MD/WrapperNew/simphony-openfoam/foam_controlwrapper/foam_controlwrapper.py", line 91, in run
    solver, self.SP_extensions, self.CM_extensions)
  File "/W5/ras/SimPhoNy/Kopplung_CFD-MD/WrapperNew/simphony-openfoam/foam_controlwrapper/foam_files.py", line 152, in modify_files
    control = ParsedParameterFile(boundaryFile, boundaryDict=True)
  File "/home/ras/.local/lib/python2.7/site-packages/PyFoam/RunDictionary/ParsedParameterFile.py", line 85, in __init__
    self.readFile()
  File "/home/ras/.local/lib/python2.7/site-packages/PyFoam/RunDictionary/FileBasis.py", line 98, in readFile
    self.openFile()
  File "/home/ras/.local/lib/python2.7/site-packages/PyFoam/RunDictionary/FileBasis.py", line 84, in openFile
    self.fh=gzip.open(self.name+".gz",mode)
  File "/usr/lib64/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib64/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/W5/ras/SimPhoNy/Kopplung_CFD-MD/WrapperNew/simphony-openfoam/foam_controlwrapper/examples/poiseuille/constant/polyMesh/boundary.gz'
Closing remaining open files:poiseuille/poiseuille.cuds...done

**Comment by khiltunen** [comment]
This all will be changed when we have enough properties on SimPhony core to create boundary sets and use specific BoundaryCondition class. Now the boundaries must be named as boundary0, boundary1,..., while the boundary faces are marked using CUBA.LABEL which must be a numeric value. Also when boundaries are directly specified as list of faces all the operations are going to be much faster. So this is just a temporary solution to get things going on.
