### ISSUE TITLE
Exception running droplet impact simulation

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-openfoam#98]
I get the following exception running the droplet experiment

```
Default patch type set to empty
Case directory  /tmp/tmpVfJ_xU/droplet_mesh
Traceback (most recent call last):
  File "d5.py", line 250, in <module>
    sim.run()
  File "/home/sborini/simphony/local/lib/python2.7/site-packages/simphony/cuds/simulation.py", line 37, in run
    self._wrapper.run(*args, **kwargs)
  File "/home/sborini/simphony/local/lib/python2.7/site-packages/foam_controlwrapper/foam_controlwrapper.py", line 77, in run
    modifyFields(mesh, cuds, solver)
  File "/home/sborini/simphony/local/lib/python2.7/site-packages/foam_internalwrapper/foam_dicts.py", line 1463, in modifyFields
    condition, mesh._foamPhaseNameToMaterial, solver)
  File "/home/sborini/simphony/local/lib/python2.7/site-packages/foam_internalwrapper/foam_dicts.py", line 1335, in get_foam_boundary_condition
    variable))
ValueError: Boundary condition not supported:
 condition: TotalPressureCondition
 variable: CUBA.DYNAMIC_PRESSURE
```

**Comment by khiltunen** [comment]
There is a working branch 'support-point-data' where this Boundary condition is included. It was waiting to get feedback but i think that it can be merged.
